server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: doctor_service
          uri: http://localhost:8081
          predicates:
            - Path=/doctors/**
        - id: patient_service
          uri: http://localhost:8082
          predicates:
            - Path=/patients/**
